### ISSUE TITLE
App is not functioning after login

### ISSUE THREAD

**Issue by SaranyaChowdary** [samurailens/GGrb#10]
The app is not responding after user login. Check the video for more details.

https://drive.google.com/file/d/0B-VY0mB4yY6mQnM2RlV2MUtDN2c/view?usp=sharing

**Comment by samurailens** [comment]
Changing the location seems to work fine.
Changing the location after going to favourites is not working, that is because your application has already crashed. This is again a back-end issue because the API response has changed after the application is released.
