### ISSUE TITLE
adding address

### ISSUE THREAD

**Issue by Hitechverma** [samurailens/GGrb#11]
After login, i tried to add one address in my account, it added normally but not to my account only to the guest account which app has freshly created.

**Comment by samurailens** [comment]
I did not understand this. 
Guest User will not see his address list in profile. Only in checkout screen, he will see his Address list. 
Can you elaborate the whole scenario?

**Comment by Hitechverma** [comment]
I have logged in and then created an address in checkout also but in the backend, the user associated with that address was the guest user, not my logged in user.

**Comment by samurailens** [comment]
yes. Definitely, that would be the case in the current version. We have not integrated Social Login feature with the backend.. so you would still see him as a guest user.  'isGuest' model was not integrated into it. Once integrated, then you will see him as registered user.
