### ISSUE TITLE
Item quantity increment/decrement issue in the cart

### ISSUE THREAD

**Issue by SaranyaChowdary** [samurailens/GGrb#13]
1: Item quantity count is going negative - check the below image

![screenshot_2017-04-15-06-14-16-345_in getgrub getgrub499402](https://cloud.githubusercontent.com/assets/15210044/25059390/af9efcca-21a3-11e7-99dc-80e159151109.png)

2: When we make the item quantity 0 still the amount in the subtotal section is displaying for 1 unit: check the below image

![screenshot_2017-04-15-06-15-47-386_in getgrub getgrub499402](https://cloud.githubusercontent.com/assets/15210044/25059431/48f28d2e-21a4-11e7-91ad-69ab16d73fd0.png)

3: Also if the item quantity is zero why it is still showing in the cart. It should simply vanish.

**Comment by samurailens** [comment]
Please discuss with Hitesh, this has to be handled by him.
We are not managing the cart, on the client. We retrieve data from the server.

**Comment by Hitechverma** [comment]
bro this is the looping issue whatever we add to the cart, the last item will always remain in UI even after we delete it.
if the data is always fetched from the server and cart is empty in response, it should not show anything in the cart but it is showing
