### ISSUE TITLE
Signup & Login screen

### ISSUE THREAD

**Issue by SaranyaChowdary** [samurailens/GGrb#3]
![screen_1](https://cloud.githubusercontent.com/assets/15210044/25055503/da8ed900-2180-11e7-8028-7db4421f69ec.png)
![screen_2](https://cloud.githubusercontent.com/assets/15210044/25055505/de1968ce-2180-11e7-9c4e-a51c1ff4d10e.png)

1. Replace Screen_1 with Screen_2 to avoid one extra step

**Comment by samurailens** [comment]
Please discuss with others get back. 
Why this was not discussed, when we shared screenshots one week back?
