### ISSUE TITLE
Payment issues

### ISSUE THREAD

**Issue by SaranyaChowdary** [samurailens/GGrb#5]
1: Payment_id Alert : Getting an alert after Razor pay success  
![17967983_1684665141840376_627346609_o](https://cloud.githubusercontent.com/assets/15210044/25059052/eaa0cf0c-219d-11e7-853f-04cc7073fc7d.png)

2: Amount increased for no reason check the below image
![17949882_1684665305173693_1227020522_o](https://cloud.githubusercontent.com/assets/15210044/25059079/35b7e386-219e-11e7-943a-584026a2b137.png)

**Comment by samurailens** [comment]
The alert message was for debugging. Should have been removed. Price computation was totally not expected. We will look into this.
