### ISSUE TITLE
menu bar

### ISSUE THREAD

**Issue by Hitechverma** [samurailens/GGrb#8]
- option for 'Mains' is missing 

- the panel should be swipeable between categories(swipe to go to next category)

- after spending some time on the app, all menu will be shown in a single category and switch between categories and cities will stop working.

**Comment by samurailens** [comment]
*after spending some time on the app, all menu will be shown in a single category and switch between categories and cities will stop working* This is because of backend issue with favourites. App had already crashed when you opened Favs.
